# Site settings
title: Competitive Programming Club
baseurl: ""
url: "http://cpc.cpsc.ucalgary.ca"
email: psc.uofc@gmail.com
facebook: https://www.facebook.com/CompetitiveProgrammingClub
twitter: https://twitter.com/ucalgary_cpc
github: https://github.com/ProblemSolvingClub

current_practice_contest: /practice/2017-03-15/

# Build settings
markdown: kramdown
